-- ============================================================
-- KEMBORN — VERİTABANI ŞEMASI
-- ============================================================
-- Bu dosya, boş bir PostgreSQL veritabanını sıfırdan kurmak içindir.
-- Şema bugüne kadar sadece canlı veritabanının içinde yaşıyordu; veritabanı
-- kaybolsa yeniden oluşturacak hiçbir kayıt yoktu. Artık burada.
--
-- KULLANIM (boş bir veritabanına):
--   psql -h localhost -p 5432 -U postgres -d postgres -f db/schema.sql
--   psql -h localhost -p 5432 -U postgres -d postgres -f db/seed.sql
--
-- MEVCUT bir veritabanını güncellemek için bu dosyayı DEĞİL,
-- db/migrations/ altındaki dosyaları çalıştır.
--
-- NOT: Aşağıdaki yapı, çalışan veritabanından pg_dump ile alınmıştır.
-- Bilinen tutarsızlıklar dosya sonunda "BİLİNEN SORUNLAR" başlığında listelidir.
-- ============================================================

-- ------------------------------------------------------------
-- KULLANICILAR
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            character varying(255) NOT NULL,
    email               character varying(255) NOT NULL UNIQUE,
    password_hash       text NOT NULL,
    created_at          timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    role                character varying(20) DEFAULT 'user',
    phone               character varying(20),
    address             text,
    -- Şifremi unuttum akışı: tek kullanımlık token ve son geçerlilik zamanı
    reset_token         text,
    reset_token_expiry  timestamp without time zone
);

-- ------------------------------------------------------------
-- ÜRÜNLER
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                character varying(255) NOT NULL,
    short_description   character varying(255),
    page_description    text,
    long_description    text,
    price               numeric(10,2) NOT NULL,
    -- Renk listesi: ["Siyah", "Beyaz"]
    colors              jsonb,
    -- Renksiz üründe tek stok; renkli üründe renk stoklarının TOPLAMI
    stock_quantity      integer DEFAULT 0,
    -- Renk bazlı stok: {"Siyah": 5, "Beyaz": 2}
    stock_by_color      jsonb DEFAULT '{}'::jsonb,
    technical_specs     jsonb,
    warranty_info       character varying(255),
    -- Kapak görseli = images dizisindeki ilk görsel (geriye dönük uyumluluk için ayrıca tutuluyor)
    image_url           text,
    images              jsonb DEFAULT '[]'::jsonb,
    video_url           text,
    -- false ise ürün müşteri tarafında hiç görünmez ve sipariş edilemez
    is_visible          boolean DEFAULT true,
    is_popular          boolean DEFAULT false,
    badge               character varying(50) DEFAULT NULL,
    sort_order          integer DEFAULT 0
);

-- ------------------------------------------------------------
-- SİPARİŞLER
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Misafir siparişlerinde NULL kalır; müşteri bilgisi guest_* alanlarındadır.
    user_id             integer REFERENCES users(id),
    -- KB-1000, KB-1001 ... (order_number_seq'ten üretilir)
    order_number        character varying(50) NOT NULL UNIQUE,
    -- ÖDEME BEKLENİYOR / ÖDENDİ / HAZIRLANIYOR / KARGODA / TAMAMLANDI /
    -- İPTAL EDİLDİ / ÖDEME BAŞARISIZ / TUTAR UYUŞMAZLIĞI
    status              character varying(50) DEFAULT 'HAZIRLANIYOR',
    -- DİKKAT: Bu tutarı sunucu hesaplar, istemciden gelen değere asla güvenilmez.
    total_amount        numeric(10,2) NOT NULL,
    shipping_address    text,
    tracking_number     character varying(100),
    payment_method      character varying(50) DEFAULT 'Kredi Kartı',
    created_at          timestamp with time zone DEFAULT CURRENT_TIMESTAMP,

    -- --- MİSAFİR (ÜYELİKSİZ) SİPARİŞ ---
    -- Üye siparişlerinde NULL; misafirde iletişim bilgisi burada saklanır
    -- (users tablosunda karşılığı olmadığı için).
    guest_name          character varying(255),
    guest_email         character varying(255),
    guest_phone         character varying(20),
    -- Misafirin kendi siparişine erişmesini sağlayan tahmin edilemez anahtar.
    -- Üyede oturum var; misafirde ödeme başlatma ve durum sorgulama bununla doğrulanır.
    access_token        character varying(64)
);

-- Misafir sipariş sorgulama (sipariş no + e-posta) ve erişim anahtarı aramaları
CREATE INDEX IF NOT EXISTS orders_guest_email_idx  ON orders (LOWER(guest_email));
CREATE INDEX IF NOT EXISTS orders_access_token_idx ON orders (access_token);

-- Sipariş numarası üreteci. KB-1000'den başlar.
CREATE SEQUENCE IF NOT EXISTS order_number_seq START WITH 1000 INCREMENT BY 1;

-- ------------------------------------------------------------
-- SİPARİŞ KALEMLERİ
-- ------------------------------------------------------------
-- product_name ve price BİLEREK burada kopyalanır ("snapshot"): ürün sonradan
-- silinse veya fiyatı değişse bile geçmiş sipariş olduğu gibi kalır.
-- Bu yüzden ürün silinirken product_id NULL'a çekilir, satır silinmez.
CREATE TABLE IF NOT EXISTS order_items (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id            integer REFERENCES orders(id) ON DELETE CASCADE,
    product_id          integer REFERENCES products(id),
    product_name        character varying(255) NOT NULL,
    quantity            integer NOT NULL,
    price               numeric(10,2) NOT NULL,
    color               character varying(50)
);

-- ------------------------------------------------------------
-- FAVORİLER
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS favorites (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- DİKKAT: users.id integer olmasına rağmen bu sütun varchar. Bkz. BİLİNEN SORUNLAR.
    user_id             character varying(255),
    product_id          integer REFERENCES products(id),
    added_at            timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, product_id)
);

-- ------------------------------------------------------------
-- MAĞAZA AYARLARI (her zaman TEK satır, id = 1)
-- ------------------------------------------------------------
-- Kod bu tabloyu her zaman "WHERE id = 1" ile okur/yazar. id=1 satırı yoksa
-- ayarlar sayfası boş gelir ve güncelleme hiçbir satıra dokunmaz.
-- Bu satırı db/seed.sql oluşturur.
CREATE TABLE IF NOT EXISTS store_settings (
    id                      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Müşteriye gösterilen kargo yazısı. Elle girilmez; shipping_fee ve
    -- free_shipping_threshold değerlerinden sunucu tarafından üretilir.
    shipping_text           character varying(255),
    shipping_fee            numeric DEFAULT 99.90,
    free_shipping_threshold numeric DEFAULT 1000,

    warranty_badge_text     character varying(255),
    warranty_tab_title      character varying(255),
    warranty_tab_bullets    text,

    customer_service_phone  character varying(255),
    whatsapp_phone          character varying(255),
    support_email           character varying(255),
    office_address          character varying(255),

    distance_selling_policy text,
    privacy_policy          text,
    delivery_return_policy  text,

    -- Pazaryeri bağlantıları (Mağazalarımız sayfası)
    trendyol_url            text,
    hepsiburada_url         text,
    n11_url                 text,

    -- Sosyal medya bağlantıları (Sosyal Medyalarımız sayfası)
    instagram_url           text,
    youtube_url             text,
    tiktok_url              text
);

-- ============================================================
-- BİLİNEN SORUNLAR (henüz düzeltilmedi, bilerek olduğu gibi bırakıldı)
-- ============================================================
-- 1) favorites.user_id  character varying(255)  →  users.id integer.
--    Tip uyuşmuyor ve users tablosuna foreign key YOK. Bu yüzden silinmiş bir
--    kullanıcının favorileri tabloda öksüz kalabiliyor. Düzeltmek veri
--    dönüşümü gerektirdiği için ayrı bir migration'a bırakıldı.
--
-- 2) products.name, short_description gibi arama yapılan sütunlarda index yok.
--    ILIKE '%...%' aramaları ürün sayısı arttıkça yavaşlayacak.
--
-- 3) orders.status serbest metin. Geçerli değerler yukarıda yorumda yazılı ama
--    veritabanı seviyesinde CHECK kısıtı ya da enum ile zorlanmıyor.
